// Config bridge — emits governance.config.json as a typed module the UI can import.
//
// The UI is static: it cannot read a file at the repository root at runtime. This
// generator is how the project name and layout reach the browser — regenerated by
// every sync, so editing governance.config.json is the only configuration step.

import { writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

import { config } from './project-paths.mjs'

const scriptDirectory = path.dirname(fileURLToPath(import.meta.url))
const outputPath = path.join(path.resolve(scriptDirectory, '..'), 'src', 'data', 'config.ts')

const generatedSource = `// Generated by scripts/generate-config.mjs from governance.config.json. Do not edit manually.
export const dashboardConfig = ${JSON.stringify(
  {
    projectName: config.projectName,
    projectShortName: config.projectShortName,
  },
  null,
  2,
)} as const
`

writeFileSync(outputPath, generatedSource)
console.log(`Config: emitted for "${config.projectName}"`)
console.log(`Generated ${path.relative(path.resolve(scriptDirectory, '..'), outputPath)}`)
