#!/usr/bin/env bash
# Regenerate ledger/<week>/README.md — the per-week index of daily files.
#
# Generated, not hand-kept, for the reason D0 exists: a hand-maintained count drifts,
# and this one would drift every single day. Run it after adding a day's file.
#
# Usage: scripts/generate-ledger-index.sh [week ...]   (defaults to every week folder)
set -uo pipefail

root="$(git rev-parse --show-toplevel 2>/dev/null)" || {
  echo "Not inside a git repository."; exit 1; }

weeks=("$@")
if [ ${#weeks[@]} -eq 0 ]; then
  while IFS= read -r d; do weeks+=("$(basename "$d")"); done \
    < <(find "${root}/ledger" -maxdepth 1 -type d -name '20*-W*' | sort)
fi

for week in "${weeks[@]}"; do
  dir="${root}/ledger/${week}"
  [ -d "$dir" ] || { echo "skip ${week} — no such folder"; continue; }

  total=0; days=0
  rows=""
  for f in "$dir"/[0-9]*.md; do
    [ -e "$f" ] || continue
    day="$(basename "$f" .md)"
    ids="$(grep -oE "^## ${week}-[0-9]+" "$f" | sed 's|^## ||')"
    n="$(printf '%s\n' "$ids" | grep -c . || true)"
    [ "$n" -eq 0 ] && continue
    first="$(printf '%s\n' "$ids" | head -1)"; last="$(printf '%s\n' "$ids" | tail -1)"
    span="$first"; [ "$n" -gt 1 ] && span="$first … $last"
    rows="${rows}| [\`${day}\`](${day}.md) | ${n} | ${span} |"$'\n'
    total=$(( total + n )); days=$(( days + 1 ))
  done

  {
    echo "# ${week}"
    echo
    echo "Append-only execution log. Format and rules: \`ledger/README.md\`."
    echo
    echo "| Day | Entries | Ids |"
    echo "|---|---:|---|"
    printf '%s' "$rows"
    echo
    echo "**${total} entries across ${days} days.**"
    echo
    echo "Generated by \`scripts/generate-ledger-index.sh\` — do not hand-edit."
  } > "${dir}/README.md"
  echo "${week}: ${total} entries across ${days} days"
done
